// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package otps_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OtpServiceClient is the client API for OtpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OtpServiceClient interface {
	GetOtp(ctx context.Context, in *GetOtpForPhoneRequest, opts ...grpc.CallOption) (*GetOtpForPhoneResponse, error)
	ValidateOtp(ctx context.Context, in *AuthValidateOtpRequest, opts ...grpc.CallOption) (*AuthValidateOtpResponse, error)
}

type otpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOtpServiceClient(cc grpc.ClientConnInterface) OtpServiceClient {
	return &otpServiceClient{cc}
}

func (c *otpServiceClient) GetOtp(ctx context.Context, in *GetOtpForPhoneRequest, opts ...grpc.CallOption) (*GetOtpForPhoneResponse, error) {
	out := new(GetOtpForPhoneResponse)
	err := c.cc.Invoke(ctx, "/OtpService/GetOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *otpServiceClient) ValidateOtp(ctx context.Context, in *AuthValidateOtpRequest, opts ...grpc.CallOption) (*AuthValidateOtpResponse, error) {
	out := new(AuthValidateOtpResponse)
	err := c.cc.Invoke(ctx, "/OtpService/ValidateOtp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OtpServiceServer is the server API for OtpService service.
// All implementations must embed UnimplementedOtpServiceServer
// for forward compatibility
type OtpServiceServer interface {
	GetOtp(context.Context, *GetOtpForPhoneRequest) (*GetOtpForPhoneResponse, error)
	ValidateOtp(context.Context, *AuthValidateOtpRequest) (*AuthValidateOtpResponse, error)
	mustEmbedUnimplementedOtpServiceServer()
}

// UnimplementedOtpServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOtpServiceServer struct {
}

func (UnimplementedOtpServiceServer) GetOtp(context.Context, *GetOtpForPhoneRequest) (*GetOtpForPhoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOtp not implemented")
}
func (UnimplementedOtpServiceServer) ValidateOtp(context.Context, *AuthValidateOtpRequest) (*AuthValidateOtpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateOtp not implemented")
}
func (UnimplementedOtpServiceServer) mustEmbedUnimplementedOtpServiceServer() {}

// UnsafeOtpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OtpServiceServer will
// result in compilation errors.
type UnsafeOtpServiceServer interface {
	mustEmbedUnimplementedOtpServiceServer()
}

func RegisterOtpServiceServer(s grpc.ServiceRegistrar, srv OtpServiceServer) {
	s.RegisterService(&OtpService_ServiceDesc, srv)
}

func _OtpService_GetOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOtpForPhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtpServiceServer).GetOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OtpService/GetOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtpServiceServer).GetOtp(ctx, req.(*GetOtpForPhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OtpService_ValidateOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthValidateOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtpServiceServer).ValidateOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OtpService/ValidateOtp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtpServiceServer).ValidateOtp(ctx, req.(*AuthValidateOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OtpService_ServiceDesc is the grpc.ServiceDesc for OtpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OtpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OtpService",
	HandlerType: (*OtpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOtp",
			Handler:    _OtpService_GetOtp_Handler,
		},
		{
			MethodName: "ValidateOtp",
			Handler:    _OtpService_ValidateOtp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otps_v1/otps_v1.proto",
}
